name: Hello Worl
on:
  pull_request:
    types: [opened]
jobs: 
  startup:
    name: Runnstartup script
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  build:
    name: Here is my build task
    runs-on: ubuntu-latest
    needs: startup
    steps:
     - run: gh pr comment $PR_URL --body "thanks for PR. we will review shortly"
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
         PR_URL: ${{ github.event.pull_request.html_url }}