name: Hello World
on:
  pull_request:
    types: [opened]
jobs: 
  startup:
    name: Run startup script
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  build:
    name: Here is my build task
    runs-on: ubuntu-latest
    needs: startup
    steps:
    - name: Comment on PR
    - run: gh pr comment $PR_URL --body "thanks for PR. we will review shortly"
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
         PR_URL: ${{ github.event.pull_request.html_url }}
    - name: Checkour code
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Check for Buttons
      run: ./.github/scripts/checker.sh
      env:
        FILE: ./src/components/Buttons.js